name: CI

on:
  push:
    branches: [main]
  workflow_dispatch:
    inputs:
      ONETBB_BRANCH:
        required: true
        default: master

jobs:
  build:
    runs-on: [ubuntu-20.04]
    steps:
      - name: Checkout repos
        uses: actions/checkout@v2
      - run: echo ${{ matrix.test }}

  tests:
    runs-on: [ubuntu-20.04]
    needs: [build]
    if: ${{ !failure() }}
    steps:
      - name: Checkout repos
        uses: actions/checkout@v2
      - run: echo ${{ matrix.test }}
  
