name: CI

on:
  push:
    branches: [main]
  workflow_dispatch:
    inputs:
      ONETBB_BRANCH:
        required: true
        default: master
        
jobs:
  ubuntu-testing-1:
    runs-on: [macos-10.15]
    env:
      test: ${{ matrix.test }}
    steps:
      - run: |
          python3 -m pip install openpyxl
          python3 -m pip install tbb4py
          python3 -m pip show tbb4py
          python3 -m tbb -h
          
