name: CI

on:
  push:
    branches: [main]
  workflow_dispatch:
    inputs:
      ONETBB_BRANCH:
        required: true
        default: master
        
jobs:
  ubuntu-testing-1:
    runs-on: [ubuntu-latest]
    strategy:
      matrix:
        test: [value1, value2]
    outputs:
      device_first: ${{ steps.set-device.outputs.device_first }}
      device_second: ${{ steps.set-device.outputs.device_second }} 
    steps:
      - uses: actions/checkout@v2
      - id: set-device
        run: |
          if [[ ${{ matrix.test == 'value1' }} ]]; then 
            echo "::set-output name=device_first::true"
            echo aaaa
          else
            echo "::set-output name=device_second::false"
          fi

  aggregate:
    runs-on: [ubuntu-latest]
    needs: [ubuntu-testing-1]
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - id: set-matrix
        run: |
          matrix='{"include":['
          if [[ '${{ needs.ubuntu-testing-1.outputs.device_first }}' == 'true' ]]; then
            matrix=${matrix}'{"test": "value1"}'
          fi
          if [[ '${{ needs.ubuntu-testing-1.outputs.device_second }}' == 'false' ]]; then
            matrix=${matrix}',{"test": "value2"}'
          fi
          matrix=${matrix}']}'
          echo "::set-output name=matrix::${matrix}"
          echo ${matrix}

  ubuntu-testing-2:
    runs-on: [ubuntu-latest]
    needs: [aggregate]
    strategy:
      matrix: ${{ fromJson(needs.aggregate.outputs.matrix) }}
    steps:
      - uses: actions/checkout@v2
      - run: echo aa
