name: CI

env:
  my_var: test

on:
  push:
    branches: [main]

  pull_request:
    branches: [main]
    types:
      - opened
      - synchronize
      - reopened

jobs:
  windows-testing:
    runs-on: [windows-2019]
    steps:
      #- name: Get oneDPL
      #  run: git clone --depth 1 https://github.com/oneapi-src/oneDPL.git
      - name: Install oneAPI Compiler
        shell: cmd
        run: |
          %CONDA%\Scripts\activate
          conda install -c intel dpcpp_impl_win-64
          dpcpp --version
