name: CI

on:
  push:
    branches: [main]
    
jobs:
  build:
    runs-on: [ubuntu-20.04]
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v2
      - name: Get oneTBB
        run: git clone --depth 1 https://github.com/oneapi-src/onetbb.git
      - name: Run testing
        run: |
          cd onetbb && mkdir build && cd build
          cmake ..
          make -j2 test_parallel_for
          ctest -R "^test_parallel_for$"
