name: CI

on:
  push:
    branches: [main]
  workflow_dispatch:
    inputs:
      ONETBB_BRANCH:
        required: true
        default: master
        
jobs:
  ubuntu-testing-1:
    runs-on: [macos-10.15]
    steps:
      - run: |
          python3 -m pip install openpyxl
          python3 -m pip install tbb4py
          ls -la ~/
          ls -la ~/Library/Python/3.8/lib
          python3 -m tbb -h
