name: CI

on:
  push:
    branches: [main]
  workflow_dispatch:
    inputs:
      ONETBB_BRANCH:
        required: true
        default: master
        
jobs:
  test1:
    runs-on: [ubuntu-latest]
    container:
      image: ubuntu:latest
      volumes:
        - /path/to/file:/path/to/file
    steps:
      - uses: actions/checkout@v2
      - run: ls -la
