name: CI

env:
  my_var: test

on:
  push:
    branches: [main]

  pull_request:
    branches: [main]
    types:
      - opened
      - synchronize
      - reopened

jobs:
  pull-request-run:
    runs-on: [ubuntu-18.04]
    if: github.event_name == 'pull_request'
    steps:
      - name: Test step
        run: |
          echo "test-42" > test.txt
      - name: Cache
        uses: actions/cache@v2
        with:
          path: test.txt
          key: test-key
          
  push-run:
    runs-on: [ubuntu-18.04]
    if: github.event_name == 'push'
    steps:
      - name: Cache
        uses: actions/cache@v2
        with:
          path: test.txt
          key: test-key
      - name: Print
        run: cat test.txt
        
