name: CI

on:
  push:
    branches: [main]
  workflow_dispatch:
    inputs:
      ONETBB_BRANCH:
        required: true
        default: master
        
jobs:
  ubuntu-testing-1:
    runs-on: [ubuntu-20.04]
    steps:
      - run: echo ttest

  ubuntu-testing-2:
    runs-on: [ubuntu-20.04]
    needs: [ubuntu-testing-1]
    if: always()
    steps:
      - run: echo test

  ubuntu-testing-3:
    runs-on: [ubuntu-20.04]
    needs: [ubuntu-testing-2]
    steps:
      - run: echo test
