name: CI

on:
  push:
    branches: [main]
  workflow_dispatch:
    inputs:
      ONETBB_BRANCH:
        required: true
        default: master
        
jobs:
  test1:
    runs-on: [ubuntu-latest]
    if: matrix.test == 'aaa'
    steps:
      - uses: actions/checkout@v2
      - run: ls
