name: CI

on:
  workflow_dispatch:

jobs:
  ubuntu-run:
    runs-on: ['${{ matrix.os }}']
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-20.04
            cxx_standard: 20
            cxx_compiler: g++-10
            c_compiler: gcc-10
            build_type: debug
    steps:
      - name: Get oneTBB
        run: git clone https://github.com/oneapi-src/oneTBB.git --depth 1 onetbb
      - name: Run testing
        run: |
          cd onetbb
          mkdir build
          cd build
          cmake -DTBB4PY_BUILD=ON -DCMAKE_CXX_COMPILER=g++ -DCMAKE_C_COMPILER=gcc ..
          make VERBOSE=1 -j2 python_build
          ctest -R python_test --output-on-failure --timeout 180
          
