name: CI

on:
  push:
    branches: [main]
  workflow_dispatch:
    inputs:
      ONETBB_BRANCH:
        required: true
        default: master
        
jobs:
  test1:
    runs-on: [ubuntu-latest]
    if: github.event_name != 'schedule'
    steps:
      - name: Test
        run: |
          mkdir test
          echo "aa" > test/run.log
          echo "aa" > test/run2.log
      - name: Save artifacts
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: test
          path: test
          retention-days: 2
