name: CI

env:
  my_var: test

on:
  push:
    branches: [main]

  pull_request:
    branches: [main]
    types:
      - opened
      - synchronize
      - reopened

jobs:
  ubuntu-run:
    runs-on: [ubuntu-18.04]
    steps:
      - name: Get oneTBB
        run: git clone https://github.com/oneapi-src/oneTBB.git --depth 1 onetbb
      - name: Run testing
        env:
          TEST: ${{ env.my_var }}
        run: |
          echo $TEST
          echo $my_var
