name: CI

on:
  push:
    branches: [main]
  workflow_dispatch:
    inputs:
      ONETBB_BRANCH:
        required: true
        default: master

jobs:
  windows-testing:
    runs-on: ['windows-2019']
    timeout-minutes: 45
    steps:
      - uses: actions/checkout@v2
      - name: Run testing
        run: |
          $ErrorActionPreference = 'Stop'
          $env:ErrorActionPreference = 'Stop'
          cmake ..
          ctest
          echo "test"
