name: CI

env:
  my_var: test

on:
  push:
    branches: [main]

  pull_request:
    branches: [main]
    types:
      - opened
      - synchronize
      - reopened

jobs:
  linux-testing:
    runs-on: [ubuntu-20.04]
    steps:
      - name: Test
        run: |
          $CONDA/bin/conda install -c intel dpcpp_linux-64
          export PATH=${CONDA}/bin:${CONDA}/include:${CONDA}/lib:${PATH}
          dpcpp --version
  
  windows-testing:
    runs-on: [windows-2019]
    steps:
      - uses: actions/checkout@v2
      - name: Install oneAPI Compiler
        shell: cmd
        run: |
          echo ::debug::hjsdajfja klsdfk alksjdlfjlk aslkdflkasd
          exit 0
          call %CONDA%/condabin/conda.bat activate base
          conda install -c intel dpcpp_win-64
      - name: Install oneTBB
        shell: cmd
        run: |
          call %CONDA%/condabin/conda.bat activate base
          conda install -c intel tbb-devel
      - name: Get oneDPL
        run: git clone --depth 1 https://github.com/oneapi-src/oneDPL.git onedpl
      - name: Run testing
        shell: cmd
        run: |
          call %CONDA%/condabin/conda.bat activate base
          cd onedpl && mkdir build && cd build
          call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvarsall.bat" x64
          set INCLUDE=%CONDA_PREFIX%\Library\include;%INCLUDE%
          set LIB=%CONDA_PREFIX%\Library\lib;%LIB%
          set OCL_ICD_FILENAMES=%CONDA_PREFIX%\Library\lib\intelocl64.dll
          cmake -G "Ninja" -DCMAKE_TOOLCHAIN_FILE=../cmake/windows-dpcpp-toolchain.cmake -DCMAKE_CXX_COMPILER=dpcpp -DONEDPL_BACKEND=dpcpp -DONEDPL_DEVICE_TYPE=CPU -DCMAKE_BUILD_TYPE=release ..
          ninja -j 2 -v sycl_iterator.pass
          ctest --timeout 360 -C release --output-on-failure -R sycl_iterator.pass
