name: CI

on:
  push:
    branches: [main]
  workflow_dispatch:
    inputs:
      ONETBB_BRANCH:
        required: true
        default: master
        
jobs:
  ubuntu-testing-1:
    runs-on: [macos-10.15]
    steps:
      - run: |
          wget https://registrationcenter-download.intel.com/akdlm/irc_nas/18212/m_cpp-compiler-classic_p_2021.4.0.248_offline.dmg
          7z x m_cpp-compiler-classic_p_2021.4.0.248_offline.dmg
          ls -la
