name: CI

on:
  push:
    branches: [main]
  workflow_dispatch:
    inputs:
      ONETBB_BRANCH:
        required: true
        default: master
        
jobs:
  ubuntu-testing-1:
    runs-on: [ubuntu-20.04]
    strategy:
      matrix:
        var1: [test1, test2, test3]
        var2: [test1, test2, test3]
    container:
      image: fedora:35
    steps:
      - uses: actions/checkout@v2
