name: CI

env:
  my_var: test

on:
  push:
    branches: [main]

  pull_request:
    branches: [main]
    types:
      - opened
      - synchronize
      - reopened

jobs:
  pull-request-run:
    runs-on: [ubuntu-18.04]
    steps:
      - name: Test step
        run: |
          echo ${{ github.sha[0] }}
          
