name: CI

env:
  my_var: test

on:
  push:
    branches: [main]

  pull_request:
    branches: [main]
    types:
      - opened
      - synchronize
      - reopened

jobs:
  my_build:
    runs-on: [ubuntu-20.04]
    steps:
      - uses: actions/checkout@v2
      - name: Run build
        run: echo "build"
  
  my_test:
    runs-on: [ubuntu-20.04]
    steps:
      - uses: actions/checkout@v2
      - name: Run testing
        run: echo "test"
