name: CI

on:
  push:
    branches: [main]
  workflow_dispatch:
    inputs:
      ONETBB_BRANCH:
        required: true
        default: master

jobs:
  failed_job:
    runs-on: [ubuntu-20.04]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Fail
        run: exit 1

  build:
    runs-on: [ubuntu-20.04]
    needs: [failed_job]
    if: ${{ !cancelled() }}
    steps:
      - name: Checkout repos
        uses: actions/checkout@v2
      - run: echo ${{ matrix.test }}

  tests:
    runs-on: [ubuntu-20.04]
    needs: [build]
    steps:
      - name: Checkout repos
        uses: actions/checkout@v2
      - run: echo ${{ matrix.test }}
  
