name: CI

on:
  push:
    branches: [main]
  workflow_dispatch:
    inputs:
      ONETBB_BRANCH:
        required: true
        default: master
        
jobs:
  test1:
    runs-on: [ubuntu-latest]
    if: github.event_name != 'schedule'
    steps:
      - name: Test
        run: |
          echo "test"
          exit -1

  test2:
    runs-on: [ubuntu-latest]
    needs: [test1]
    if: github.event_name != 'schedule'
    steps:
      - name: Test
        run: echo "test"
