name: CI

on:
  push:
    branches: [main]
  workflow_dispatch:
    inputs:
      ONETBB_BRANCH:
        required: true
        default: master
        
jobs:
  test1:
    runs-on: [ubuntu-latest]
    steps:
      - env:
          test1: ""
          test2:
        run: |
          if [ -z ${test1} ]; then echo "test1"; fi
          if [ -z ${test2} ]; then echo "test2"; fi
          if [ -z ${test3} ]; then echo "test3"; fi
