name: CI

on:
  push:
    branches: [main]
  workflow_dispatch:
    inputs:
      ONETBB_BRANCH:
        required: true
        default: master
        
jobs:
  ubuntu-testing-1:
    runs-on: [ubuntu-latest]
    strategy:
      matrix:
        test: [value1, value2]
    outputs:
      device-1: ${{ steps.set-device.outputs.device-1 }}
      device-2: ${{ steps.set-device.outputs.device-1 }} 
    steps:
      - uses: actions/checkout@v2
      - name: set-device
        run: |
          if [[ ${{ matrix.test == 'value1' }} ]]; then 
            echo "::set-output name=device-1::true"
            echo aaaa
          else
            echo "::set-output name=device-2::false"
          fi

  aggregate:
    runs-on: [ubuntu-latest]
    needs: [ubuntu-testing-1]
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: set-matrix
        run: |
          matrix='{\"include\":['
          if [[ ${{ needs.ubuntu-testing-1.outputs.device-1 }} == 'true' ]]; then
            matrix=${matrix}'{\"test\":\"value1\"=}'
          fi
          if [[ ${{ needs.ubuntu-testing-1.outputs.device-2 }} == 'false' ]]; then
            matrix=${matrix}',{\"test\":\"value2\"=}'
          fi
          echo "::set-output name=matrix::${matrix}"
      

  ubuntu-testing-2:
    runs-on: [ubuntu-latest]
    needs: [aggregate]
    if: needs.ubuntu-testing-1.outputs.device
    strategy:
      matrix: ${{ fromJson(needs.aggregate.outputs.matrix) }}
    steps:
      - uses: actions/checkout@v2
      - run: echo aaaa
