name: CI

on:
  push:
    branches: [main]
  workflow_dispatch:
    inputs:
      ONETBB_BRANCH:
        required: true
        default: master
        
jobs:
  test1:
    runs-on: [ubuntu-latest]
    steps:
      - env:
          test1: ""
          test2:
        run: |
          chmod +x ./test.sh
          ./test.sh $test1 $test2 $test3
