name: CI

env:
  my_var: test

on:
  push:
    branches: [main]

  pull_request:
    branches: [main]
    types:
      - opened
      - synchronize
      - reopened

jobs:
  windows-testing:
    runs-on: [windows-2019]
    steps:
      - name: Init conda
        run: |
          & ${env:CONDA}\condabin\conda.bat init powershell
      - name: Get oneDPL
        run: git clone --depth 1 https://github.com/oneapi-src/oneDPL.git onedpl
      - name: Run testing
        run: |
          & ${env:CONDA}\condabin\conda.bat activate base
          cd onedpl
          mkdir build
          cd build
