name: CI

env:
  my_var: test

on:
  push:
    branches: [main]

  pull_request:
    branches: [main]
    types:
      - opened
      - synchronize
      - reopened

jobs:
  windows-testing:
    runs-on: [windows-2019]
    steps:
      #- name: Get oneDPL
      #  run: git clone --depth 1 https://github.com/oneapi-src/oneDPL.git
      - name: Install oneAPI Compiler
        run: |
          ${CONDA}\bin\conda init powershell
          ${CONDA}\bin\conda activate base
