name: CI

on:
  push:
    branches: [main]
  workflow_dispatch:
    inputs:
      ONETBB_BRANCH:
        required: true
        default: master
        
jobs:
  test1:
    runs-on: [ubuntu-latest]
    steps:
      - run: |
          jfrog -v || true
      - uses: jfrog/setup-jfrog-cli@v2
      - run: |
          jfrog -v
