name: CI

on:
  push:
    branches: [main]
  workflow_dispatch:
    inputs:
      ONETBB_BRANCH:
        required: true
        default: master
        
jobs:
  windows-testing-1:
    runs-on: [windows-latest]
    steps:
      - uses: actions/checkout@v2
      - run: |
          python -m pip install tbb4py
          python -m tbb test
