name: CI

on:
  push:
    branches: [main]
  workflow_dispatch:
    inputs:
      ONETBB_BRANCH:
        required: true
        default: master
        
jobs:
  test1:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
      - uses: jfrog/setup-jfrog-cli@v2
      - name: test
        run: ls
      - uses: jfrog/setup-jfrog-cli@v2
