name: CI

on:
  push:
  workflow_dispatch:
    inputs:
      ONETBB_BRANCH:
        required: true
        default: master
        
jobs:
  documentation:
    env:
      BUILD_TYPE: oss
    runs-on: [ubuntu-20.04]
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2
        with:
          repository: oneapi-src/onetbb
      - name: Install prerequisites
        run: |
          pip3 install git+https://github.com/executablebooks/sphinx-book-theme.git
          echo GITHUB_SHA_SHORT=${GITHUB_SHA::8} >> $GITHUB_ENV
          mkdir html
      - name: Build documentation
        run: |
          export BUILD_TYPE=${BUILD_TYPE} && sphinx-build ./doc ./html
          tar -czvf html.tar.gz html/
      - name: Save docs
        uses: actions/upload-artifact@v2.2.1
        with:
          name: oneTBB-html-docs-${{ env.GITHUB_SHA_SHORT }}
          path: html.tar.gz
      - name: Save docs
        if: ${{ always() }}
        uses: actions/upload-artifact@v2.2.1
        with:
          name: test
          path: /tmp/sphinx*
