name: CI

on:
  push:
    branches: [main]
  workflow_dispatch:
    inputs:
      ONETBB_BRANCH:
        required: true
    
jobs:
  build:
    runs-on: [ubuntu-20.04]
    if: github.event_name != 'push'
    timeout-minutes: 60
    strategy:
      matrix:
        build_type: [debug, relwithdebinfo]
    steps:
      - uses: actions/checkout@v2
      - name: Get oneTBB
        run: git clone -b ${{ github.event.inputs.ONETBB_BRANCH }} --depth 1 https://github.com/oneapi-src/onetbb.git
      - name: Run testing
        run: |
          cd onetbb && mkdir build && cd build
          cmake -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} ..
          make -j2 test_parallel_for
          ctest -R "^test_parallel_for$"
